[package]
name = "nostr-postgres-db"
version = "0.1.1"
edition = "2024"
description = "Postgres SQL storage backend for Nostr relays"
keywords = ["nostr", "database", "postgres"]
license = "MIT"

[dependencies]
nostr = { version = "0.44", features = ["std"] }
nostr-database = { version = "0.44", features = ["flatbuf"] }
tracing = { version = "0.1", default-features = false }
tokio-postgres = { version = "0.7", features = [
  "with-chrono-0_4",
  "with-serde_json-1",
] }
deadpool-postgres = "0.14"

[dev-dependencies]
nostr-relay-builder = "0.44"
tokio = { version = "1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
tracing-subscriber = "0.3"
testcontainers = "0.26"
testcontainers-modules = { version = "0.14", features = ["postgres"] }

[[example]]
name = "postgres-relay"
