name: Rust CI

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  actions: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Free up disk space
        uses: BitcreditProtocol/.github/.github/actions/free-disk-space@6de4960af50d86d1d76a813b27a9a700a68da7c8 # v1.0.0

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update

      - name: Add rustup components
        run: rustup component add clippy rustfmt

      - name: Install required cargo
        run: cargo install cargo-deny clippy-sarif sarif-fmt

      - name: Activate cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          prefix-key: "nostr-postgres"

      - name: Check
        run: cargo check --verbose

      - name: Check formatting
        run: cargo fmt -- --check
        continue-on-error: true

      - name: Clippy
        run:
          cargo clippy
          --verbose
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Cargo deny
        run: cargo deny check
        continue-on-error: true

      - name: Build
        run: cargo build --verbose

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        continue-on-error: true
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
