name: Test coverage

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update stable

      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Activate cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          prefix-key: "nostr-postgres"

      - name: Run tests
        run: cargo test --verbose
        env:
          LLVM_PROFILE_FILE: "target/coverage/prof/%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Create coverage report
        run: |
          grcov \
            --source-dir . \
            --binary-path target/debug \
            --branch \
            --excl-start 'mod tests \{' \
            --ignore 'tests/*' \
            -t lcov \
            -o lcov.info \
            target/coverage/prof

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
