name: Test coverage

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update stable

      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Activate cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          prefix-key: "bcr-relay"

      - name: Run tests
        run: cargo test --verbose
        env:
          LLVM_PROFILE_FILE: "target/coverage/prof/%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Create coverage report
        run: |
          grcov \
            --source-dir . \
            --binary-path target/debug \
            --branch \
            --excl-start 'mod tests \{' \
            --ignore 'tests/*' \
            -t lcov \
            -o lcov.info \
            target/coverage/prof

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
